mcd <- load("Multi_Cancer_Data.RData")
dfMcd <- as.data.frame(multi_cancer_data)

tumores <- grepl("Tumor", colnames(dfMcd))
normales <- grepl("Normal", colnames(dfMcd))

print(t.test(tumores, normales))
print("p-value:")
print(t.test(tumores, normales)$p.value)
readline(prompt="Press [enter] to continue")

tBreast <- grepl("Tumor__Breast_Adeno", colnames(dfMcd))
tProstate <- grepl("Tumor__Prostate_Adeno", colnames(dfMcd))
tLung <- grepl("Tumor__Lung_Adeno", colnames(dfMcd))
tColoRect <- grepl("Tumor__Colorectal_Adeno", colnames(dfMcd))
tLymph <- grepl("Tumor__Lymphoma", colnames(dfMcd))
tMelanoma <- grepl("Tumor__Melanoma", colnames(dfMcd))
tBladder <- grepl("Tumor__Bladder", colnames(dfMcd))
tUtero <- grepl("Tumor__Uterus_Adeno", colnames(dfMcd))
tLeukemia <- grepl("Tumor__Leukemia", colnames(dfMcd))
tRenal <- grepl("Tumor__Renal_Carcinoma", colnames(dfMcd))
tPancreas <- grepl("Tumor__Pancreas_Adeno", colnames(dfMcd))
tOvary <- grepl("Tumor__Ovary_Adeno", colnames(dfMcd))
tMesothelioma <- grepl("Tumor__Mesothelioma", colnames(dfMcd))
tCNSGliob <- grepl("Tumor__CNS_Glioblastoma", colnames(dfMcd))
tCNSMedull <- grepl("Tumor__CNS_Medulloblastoma", colnames(dfMcd))

nBreast <- grepl("Normal__Breast", colnames(dfMcd))
nProstate <- grepl("Normal__Prostate", colnames(dfMcd))
nLung <- grepl("Normal__Lung", colnames(dfMcd))
nColoRect <- grepl("Normal__Colon", colnames(dfMcd))
nLymph <- grepl("Normal__Germinal", colnames(dfMcd))
nMelanoma <- grepl("Normal__Peripheral_Blood", colnames(dfMcd))
nBladder <- grepl("Normal__Bladder", colnames(dfMcd))
nUtero <- grepl("Normal__Uterus", colnames(dfMcd))
nLeukemia <- grepl("Normal__Peripheral_Blood", colnames(dfMcd))
nRenal <- grepl("Normal__Kidney", colnames(dfMcd))
nPancreas <- grepl("Normal__Pancreas", colnames(dfMcd))
nOvary <- grepl("Normal__Ovary", colnames(dfMcd))
nMesothelioma <- grepl("Normal__Peripheral_Blood", colnames(dfMcd))
nCNSGliob <- grepl("Normal__Whole_Brain_BRAIN", colnames(dfMcd))
nCNSMedull <- grepl("Normal__Cerebellum", colnames(dfMcd))

print(t.test(tBreast, nBreast))
print("p-value:")
print(t.test(tBreast, nBreast)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tProstate, nProstate))
print("p-value:")
print(t.test(tProstate, nProstate)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tLung, nLung))
print("p-value:")
print(t.test(tLung, nLung)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tColoRect, nColoRect))
print("p-value:")
print(t.test(tColoRect, nColoRect)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tLymph, nLymph))
print("p-value:")
print(t.test(tLymph, nLymph)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tMelanoma, nMelanoma))
print("p-value:")
print(t.test(tMelanoma, nMelanoma)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tBladder, nBladder))
print("p-value:")
print(t.test(tBladder, nBladder)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tUtero, nUtero))
print("p-value:")
print(t.test(tUtero, nUtero)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tLeukemia, nLeukemia))
print("p-value:")
print(t.test(tLeukemia, nLeukemia)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tRenal, nRenal))
print("p-value:")
print(t.test(tRenal, nRenal)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tPancreas, nPancreas))
print("p-value:")
print(t.test(tPancreas, nPancreas)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tOvary, nOvary))
print("p-value:")
print(t.test(tOvary, nOvary)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tMesothelioma, nMesothelioma))
print("p-value:")
print(t.test(tMesothelioma, nMesothelioma)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tCNSGliob, nCNSGliob))
print("p-value:")
print(t.test(tCNSGliob, nCNSGliob)$p.value)
readline(prompt="Press [enter] to continue")

print(t.test(tCNSMedull, nCNSMedull))
print("p-value:")
print(t.test(tCNSMedull, nCNSMedull)$p.value)
readline(prompt="Press [enter] to continue")